services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      JWT_SECRET: a9f8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9
      MONGO_URI: mongodb://mongo:27017/accrediflow
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

